### ISSUE TITLE
event.js 的三处问题, 如变量名不对造成报错

### ISSUE THREAD

**Issue by Hext123** [CleverBamboo/event-bus#5]
你好 感谢开源 event bus 的解决方案

我在event.js 中发现了3处问题

1. [48行](https://github.com/CleverBamboo/event-bus/blob/master/event.js#L48)的 `stores` 应为 `store`

2. [60行](https://github.com/CleverBamboo/event-bus/blob/master/event.js#L60)的 `cd` 应为 `cb`

3. on订阅方法允许多次添加重复的handler, 但是off删除方法又只删除了一个之后就break了

**Comment by Hext123** [comment]
第3条或许不算bug

**Comment by CleverBamboo** [comment]
@Hext123 感谢指正，第3条不是Bug，打个比方，你订阅一个函数多少次，就相当于你买了多少把枪，你销毁一次只能销毁一把枪，不能一次销毁所有的枪。如果你要销毁全部枪，就有多少条枪，就销毁多少次
